#!/usr/bin/env bash
# Build through PEP 517 in an isolated staging tree. Wheel tags and RECORD
# are generated by the native packaging backend, never patched afterward.
set -euo pipefail
cd "$(dirname "$0")/../.."
python="${VKERNELS_PYTHON:-python3}"
out=dist
cuda=OFF
hip=OFF
while (($#)); do
  case "$1" in
    --cuda) cuda=ON ;;
    --hip) hip=ON ;;
    --python) python="$2"; shift ;;
    --output-dir|-o) out="$2"; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done
[[ "$cuda:$hip" != ON:ON ]] || { echo "Choose one GPU backend" >&2; exit 2; }
"$python" -m build --wheel --outdir "$out"   -Ccmake.define.VKERNELS_BUILD_CUDA="$cuda"   -Ccmake.define.VKERNELS_BUILD_HIP="$hip"   -Ccmake.define.Python3_EXECUTABLE="$("$python" -c 'import sys; print(sys.executable)')"
# Linux tags deliberately remain linux_<arch>. For redistribution, inspect
# with auditwheel show and repair in a matching manylinux build container.
