"""CuTe DSL code generation: emit the persistent megakernel source (§8).

The generator emits *source text* for a CuTe DSL megakernel implementing
the §8.1 device algorithm:

    for phase in compiled_phases:
        task_id = worker
        while task_id < phase.task_count:
            coordinates = phase.decode_task_id(task_id)
            run_task(phase, coordinates, arguments, workspace, scratch)
            finish_task_local_async_work()
            block_sync()
            task_id += workers
        grid_sync()          # idle workers participate too

Design constraints honored here:

* The phase loop is emitted as device control flow over a *static phase
  table* — the simplest generator of §8.1: statically selected task calls,
  no runtime Python callables or unverified device function pointers.
* Grid synchronization is emitted through a single ``grid_sync()`` seam.
  Per §8.4, current CuTe documentation does not establish a
  ``cute.arch.grid_sync()`` API; the emitted module raises at import/use
  time unless the Milestone-0 primitive has been verified. The seam is the
  one place a verified cooperative barrier (or backend extension) plugs in.
* Position stays a runtime scalar: every runtime-bound task receives
  ``position`` as an argument; task counts are static (§4.2, §1.3).

The emitted module is syntactically valid Python (tests compile() it) and
is import-safe only where ``cutlass.cute`` exists; importing it does not
by itself make the device program executable.
"""

from __future__ import annotations

from typing import Optional

from .memory import WorkspacePlan
from .schedule_phase import PhaseSchedule
from .task_ir import TaskFamily

__all__ = ["emit_megakernel_source", "TEMPLATE_NAMES"]

# Device task templates referenced by the generated kernel (M2 library).
# The generated source imports these names; their CuTe implementations are
# the reusable task bodies of §3.1.
TEMPLATE_NAMES = {
    "gemm": "linear_task",
    "layernorm": "layernorm_task",
    "rms_norm": "rms_norm_task",
    "rope": "rope_task",
    "elementwise": "elementwise_task",
    "embedding": "embedding_task",
    "cache_append": "cache_append_task",
    "attention_scores": "attention_scores_task",
    "softmax": "softmax_task",
    "attention_values": "attention_values_task",
}

_TEMPLATE_MODULE = "vkernels.compiler.device_templates"


def _fmt_params(params: dict) -> str:
    """Emit a dict literal with Python-valid syntax ({k: v}, not kwargs)."""

    def val(v):
        return repr(v) if isinstance(v, (str, float)) else str(v)

    return "{" + ", ".join(f"{k!r}: {val(v)}" for k, v in params.items()) + "}"


def emit_megakernel_source(
    schedule: PhaseSchedule,
    workspace_plan: WorkspacePlan,
    families: list[TaskFamily],
    *,
    kernel_name: str = "gpt2_megakernel",
    workers_hint: Optional[int] = None,
    threads_per_worker: int = 256,
    scratch_bytes_per_worker: int = 0,
) -> str:
    """Emit the phase-synchronous megakernel as CuTe DSL source text."""
    lines: list[str] = []
    w = lines.append

    w('"""Generated phase-synchronous megakernel (single-token GPT-2 decode).')
    w("")
    w("Generated by vkernels.compiler.codegen_cute — DO NOT EDIT.")
    w(f"Schedule: phase-synchronous, {schedule.num_phases} phases, {schedule.total_tasks} logical tasks.")
    if workers_hint is not None:
        w("Worker count P is a launch-time quantity (read from the physical grid;")
        w(f"the compiled schedule is valid for any P in [1, residency bound]; hint={workers_hint}).")
    w("")
    w("Backend capability caveat (design §8.4): grid synchronization is emitted")
    w("through the grid_sync() seam below. Current CuTe DSL documentation does")
    w("not establish cute.arch.grid_sync(); before executing this kernel, a")
    w("Milestone-0-verified cooperative grid barrier must replace the seam.")
    w("The reference executor validates the schedule logic on CPU; it does not")
    w("validate GPU synchronization or memory ordering (§15.1).")
    w('"""')
    w("")
    w("import cutlass.cute as cute")
    w(f"from {_TEMPLATE_MODULE} import (  # noqa: F401  (device task templates)")
    w("    " + ", ".join(sorted(set(TEMPLATE_NAMES.values()))) + ",")
    w(")")
    w("")
    w(f"NUM_PHASES = {schedule.num_phases}")
    w(f"THREADS_PER_WORKER = {threads_per_worker}")
    w(f"SCRATCH_BYTES_PER_WORKER = {scratch_bytes_per_worker}")
    w(f"WORKSPACE_ELEMENTS = {workspace_plan.total_elements}")
    w("")
    w("")
    w("def grid_sync():")
    w('    """The single synchronization seam (§8.4).')
    w("")
    w("    Replaced by the verified cooperative-grid barrier primitive after")
    w("    Milestone 0 capability validation on the pinned CuTe version. A")
    w("    plain counter plus polling loop is NOT a sufficient barrier")
    w("    specification (arrival/departure phases, release/acquire visibility,")
    w("    reuse protocol must all be established).")
    w('    """')
    w("    raise NotImplementedError(")
    w('        "grid_sync: Milestone-0 grid-barrier primitive not verified on this stack (§8.4)"')
    w("    )")
    w("")
    w("")
    w("# Static phase table: (kind, template, task_count, params). Task counts are")
    w("# static; only per-task work bounds depend on the runtime position p (§4.2).")
    w("_PHASES = (")

    for phase in schedule.phases:
        fam = phase.families[0]
        template = TEMPLATE_NAMES[fam.kind]
        w(f"    # phase {phase.index}: {fam.op.source_location}")
        w(f"    ({fam.kind!r}, {template}, {fam.task_count}, {_fmt_params(fam.params)}),")
    w(")")
    w("")
    w("")
    w("@cute.kernel")
    w(f"def {kernel_name}(ids, params, cache, workspace, position):")
    w("    # One persistent launch for the whole model (§1.1, §8.1).")
    w("    worker = cute.arch.block_idx()[0]")
    w("    workers = cute.arch.grid_dim()[0]")
    w("    tid = cute.arch.thread_idx()[0]")
    w("    assert tid < THREADS_PER_WORKER")
    w("    scratch = worker_local_scratch()  # SCRATCH_BYTES_PER_WORKER bytes")
    w("")
    w("    for phase_idx in range(NUM_PHASES):")
    w("        kind, template, task_count, params = _PHASES[phase_idx]")
    w("        # Stride assignment: worker b takes task ids b, b+P, ... (§8.1).")
    w("        task_id = worker")
    w("        while task_id < task_count:")
    w("            coords = decode_task_id(kind, task_id, params)")
    w("            run_task(template, coords, ids, params, cache, workspace, position, scratch)")
    w("            finish_task_local_async_work()  # task contract before reuse (§6.3)")
    w("            cute.arch.sync_warp()  # placeholder block-level collectives (§7.1)")
    w("            task_id += workers")
    w("        # Outside the tile loop: idle workers participate too (§8.3).")
    w("        grid_sync()")
    w("")
    w("")
    w("def worker_local_scratch():")
    w("    raise NotImplementedError('shared-memory scratch lowering is a device-template concern')")
    w("")
    w("")
    w("def decode_task_id(kind, task_id, params):")
    w("    # Row-major decode over each family's tile grid; mirrors TileDomain.")
    w("    raise NotImplementedError('emitted per-family by the device templates')")
    w("")
    w("")
    w("def run_task(template, coords, ids, params, cache, workspace, position, scratch):")
    w("    # Static dispatch to the selected task template with resolved buffer")
    w("    # offsets; a later generator may emit direct per-phase call sites.")
    w("    raise NotImplementedError('device dispatch is template-inlined')")
    w("")

    # Workspace layout as data, for host-side allocation and debugging.
    w("# Workspace buffer layout (elements; f32 target):")
    w("WORKSPACE_BUFFERS = (")
    for b in workspace_plan.buffers:
        w(f"    ({b.name!r}, {b.offset}, {b.numel}, {b.first_phase}, {b.last_phase}, {b.live_at_end}),")
    w(")")
    w("")
    return "\n".join(lines)
